Fixed a few bugs the the previous scripts. Added combo packages support. Added the buildtools combo package.

diff --git a/etc/tools/get-emScriptFunctions b/etc/tools/get-emScriptFunctions
--- a/etc/tools/get-emScriptFunctions
+++ b/etc/tools/get-emScriptFunctions
@@ -45,6 +45,9 @@
 #     GE_levels     - Should echo the number of folder levels counting from the
 #                     left, should the unpacker drop. This is a prevention
 #                     mechanism for tar/zipbombs.
+#     GE_update     - Should echo the list of packages to be installed instead
+#                     of this one. This function is only required for combo
+#                     systems.
 #
 #------------------------------------------------------------------------------
 
@@ -53,6 +56,7 @@ Script=${0##*/}
 path2Script=${0%/*}
 versionCacheFile=$path2Script/$Script.cache
 testFile="$Script.dumpfile.$$"
+defaultsFile="etc/defaults.sh"
 
 
 #
@@ -69,6 +73,7 @@ Usage
      $Script description
      $Script update MIRROR_URL
      $Script versions MIRROR_URL
+     $Script unroll VERSION
      $Script geturl MIRROR_URL VERSION
      $Script getversion MIRROR_URL VERSION
      $Script getfilename VERSION
@@ -81,6 +86,7 @@ Valid options (use only one per command)
   description - show the description for this application.
   update MIRROR_URL - updates the list of versions available.
   versions MIRROR_URL - show the list of versions available for this application.
+  unroll VERSION - in case of combo packages, show the list of packages; otherwise, return the same "app=version".
   geturl MIRROR_URL VERSION - get the link for the desired version to download.
   getversion MIRROR_URL VERSION - get the true version.
   getfilename VERSION - get the filename for the desired version (true version only).
@@ -99,6 +105,17 @@ USAGE
 
 
 # ---------------------------------------------------------- start of functions
+
+
+#
+# Check if function exists
+# Returns exit code 0 if found and exit code 1.
+#
+GETEM_fn_exists()
+{
+  export LC_ALL=C
+  type $1 2>/dev/null | grep " function" > /dev/null
+}
 
 
 #
@@ -122,7 +139,11 @@ GETEM_version_validation()
 #
 GETEM_showDescription()
 {
-  GE_showDesc
+  if GETEM_fn_exists GE_showDesc; then
+    GE_showDesc
+  else
+    GETEM_usage "Function 'GE_showDesc' is missing."
+  fi
 }
 
 
@@ -133,7 +154,11 @@ GETEM_showDescription()
 GETEM_update()
 {
   [ "$#" -lt 1 ] && GETEM_usage "Missing MIRROR_URL for version listing."
-  GE_update $1 $2
+  if GETEM_fn_exists GE_update; then
+    GE_update $1 $2
+  else
+    GETEM_usage "Function 'GE_update' is missing."
+  fi
 }
 
 
@@ -168,6 +193,21 @@ GETEM_geturl()
 
 
 #
+# Unroll the version $1, in case it's a combo package.
+#
+GETEM_unroll()
+{
+  [ "$#" -lt 1 ] && GETEM_usage "Missing VERSION for unrolling."
+
+  if GETEM_fn_exists GE_unroll; then
+    GE_unroll $1
+  else
+    echo $Script=$1
+  fi
+}
+
+
+#
 # Gets the real version definition, by translating the literal one.
 # Receives the mirror url $1 and the literal version $2. Needs the predefined variables "versionVar",
 # "appName" and "appDefaultSep" to be properly defined prior to sourcing this script.
@@ -177,7 +217,7 @@ GETEM_getversion()
   [ "$#" -lt 2 ] && GETEM_usage "Missing MIRROR_URL and/or VERSION for true version retrieval."
   case $2 in
   default)
-    VERSION=`. etc/defaults.sh ; eval echo "\$"$versionVar | sed 's/'${appName}${appDefaultSep}'//'`
+    VERSION=`. $defaultsFile ; eval echo "\$"$versionVar | sed 's/'${appName}${appDefaultSep}'//'`
     break
     ;;
   latest)
@@ -279,73 +319,77 @@ GETEM_purge()
 #
 GETEM_unpackFile()
 {
-  [ "$#" -lt 1 ] && GETEM_usage "Missing VERSION for unpacking."
-  FILENAME=`GETEM_getfilename $1`
-  FOLDER=`GE_getfolder $1`
-  LEVELS2KILL=`GE_levels $1`
-  DO_UNPACK_IT=1;
+  if GETEM_fn_exists GE_getfolder && GETEM_fn_exists GE_levels ; then
+    [ "$#" -lt 1 ] && GETEM_usage "Missing VERSION for unpacking."
+    FILENAME=`GETEM_getfilename $1`
+    FOLDER=`GE_getfolder $1`
+    LEVELS2KILL=`GE_levels $1`
+    DO_UNPACK_IT=1;
 
-  if [ -d $FOLDER ]; then
-    THE_ANSWER=""
-    while [ -z "$THE_ANSWER" ]; do
-      echo "The folder $FOLDER already exists. (R)emove the folder, (O)verwrite or (S)kip?"
-      read THE_ANSWER
-      case $THE_ANSWER in
-      R | r)
-        GETEM_removeFolder $1
+    if [ -d $FOLDER ]; then
+      THE_ANSWER=""
+      while [ -z "$THE_ANSWER" ]; do
+        echo "The folder $FOLDER already exists. (R)emove the folder, (O)verwrite or (S)kip?"
+        read THE_ANSWER
+        case $THE_ANSWER in
+        R | r)
+          GETEM_removeFolder $1
+          break
+          ;;
+        O | o)
+          #do nothing... simply go ahead and do it!
+          break
+          ;;
+        S | s)
+          DO_UNPACK_IT=0;
+          echo Skipping file...
+          break
+          ;;
+        *)
+          echo Invalid answer...
+          THE_ANSWER=""
+          break
+          ;;
+        esac
+      done
+      unset THE_ANSWER
+    fi
+
+    if [ ! -f "download/$FILENAME" ]; then
+      echo "Could not unpack $FILENAME"
+      exit 1
+    elif [ $DO_UNPACK_IT -eq 1 ]; then
+      case $appFileExt in
+      tar.gz)
+        mkdir -p "$FOLDER" && \
+          tar -xzf download/$FILENAME -C "$FOLDER" --strip-components=$LEVELS2KILL
         break
         ;;
-      O | o)
-        #do nothing... simply go ahead and do it!
+      tar.bz2)
+        mkdir -p "$FOLDER" && \
+          tar -xjf download/$FILENAME -C "$FOLDER" --strip-components=$LEVELS2KILL
         break
         ;;
-      S | s)
-        DO_UNPACK_IT=0;
-        echo Skipping file...
+      zip)
+        LEVEL2KILL_STR="*"
+        for level in $(seq 1 $LEVEL2KILL); do
+          LEVEL2KILL_STR="${LEVEL2KILL_STR}/*"
+        done
+
+        mkdir "$testFile" && \
+          unzip "download/$FILENAME" -d "$testFile" && \
+          mkdir -p $FOLDER > /dev/null 2>&1  && \
+          mv "$testFile"/$LEVEL2KILL_STR "$FOLDER/"
+        [ -n "$testFile" -a -d "$testFile" ] && rm -rf "$testFile"
         break
         ;;
       *)
-        echo Invalid answer...
-        THE_ANSWER=""
-        break
+        GETEM_usage "File extension '$appFileExt' is not recognized for unpacking."
         ;;
       esac
-    done
-    unset THE_ANSWER
-  fi
-
-  if [ ! -f "download/$FILENAME" ]; then
-    echo "Could not unpack $FILENAME"
-    exit 1
-  elif [ $DO_UNPACK_IT -eq 1 ]; then
-    case $appFileExt in
-    tar.gz)
-      mkdir -p "$FOLDER" && \
-        tar -xzf download/$FILENAME -C "$FOLDER" --strip-components=$LEVELS2KILL
-      break
-      ;;
-    tar.bz2)
-      mkdir -p "$FOLDER" && \
-        tar -xjf download/$FILENAME -C "$FOLDER" --strip-components=$LEVELS2KILL
-      break
-      ;;
-    zip)
-      LEVEL2KILL_STR="*"
-      for level in $(seq 1 $LEVEL2KILL); do
-        LEVEL2KILL_STR="${LEVEL2KILL_STR}/*"
-      done
-
-      mkdir "$testFile" && \
-        unzip "download/$FILENAME" -d "$testFile" && \
-        mkdir -p $FOLDER > /dev/null 2>&1  && \
-        mv "$testFile"/$LEVEL2KILL_STR "$FOLDER/"
-      [ -n "$testFile" -a -d "$testFile" ] && rm -rf "$testFile"
-      break
-      ;;
-    *)
-      GETEM_usage "File extension '$appFileExt' is not recognized for unpacking."
-      ;;
-    esac
+    fi
+  else
+    GETEM_usage "Function 'GE_getfolder' or 'GE_levels' is/are missing."
   fi
 }
 
@@ -355,9 +399,13 @@ GETEM_unpackFile()
 #
 GETEM_removeFolder()
 {
-  [ "$#" -lt 1 ] && GETEM_usage "Missing VERSION for removing folder."
-  FOLDER=`GE_getfolder $1`
-  [ -n "$FOLDER" -a -d "$FOLDER" ] && rm -rf "$FOLDER"
+  if GETEM_fn_exists GE_getfolder; then
+    [ "$#" -lt 1 ] && GETEM_usage "Missing VERSION for removing folder."
+    FOLDER=`GE_getfolder $1`
+    [ -n "$FOLDER" -a -d "$FOLDER" ] && rm -rf "$FOLDER"
+  else
+    GETEM_usage "Function 'GE_getfolder' is missing."
+  fi
 }
 
 # ------------------------------------------------------------ end of functions
@@ -379,6 +427,10 @@ versions)
   ;;
 geturl)
   GETEM_geturl $2 $3
+  break
+  ;;
+unroll)
+  GETEM_unroll $2
   break
   ;;
 getversion)
